
require 'arg'
require 'string'
require 'clang/clang-c'

require 'plib/core/option'



local files: sequence(stringview)
local output: option(stringview) = None()
local include_system_headers: boolean


local i = 1
while i <= #arg do
	if arg[i] == "-o" or arg[i] == "--output" then
		output = Some(arg[i+1])
		i = i + 1
	elseif arg[i] == "-s" or arg[i] == "--system-includes" then
		include_system_headers = true
	else
		files:push(arg[i])
	end

	i = i + 1
end



